runtime: nodejs20
env: standard
instance_class: B1

handlers:
  - url: /images/(.*)
    static_files: images/\1
    upload: images/.*
  - url: .*
    script: auto

manual_scaling:
  instances: 1